# Generated by Django 5.0.4 on 2024-04-30 20:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("create_blog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="authors",
            field=models.ManyToManyField(
                related_name="blogs", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
